(function(){'use strict';
var input=document.getElementById('exploreSearch'),results=document.getElementById('exploreResults'),explore=document.getElementById('explore');if(!input||!results||!explore)return;
var form=document.createElement('form'),submit=document.createElement('button'),status=document.createElement('p'),live=document.createElement('div'),samples=document.createElement('div');var request=null,serial=0,last='',cache=new Map(),until=0;
form.setAttribute('role','search');form.style.cssText='display:flex;gap:8px;align-items:center';submit.type='submit';submit.textContent='Search';submit.className='button';submit.style.cssText='width:auto;min-height:50px;padding:0 16px;flex:none';input.parentNode.insertBefore(form,input);form.append(input,submit);input.placeholder='Search real products or brands';input.setAttribute('aria-label','Search real products or brands');status.setAttribute('role','status');status.setAttribute('aria-live','polite');status.className='hint';status.style.cssText='margin:0 0 8px';form.after(status);live.className='productlist';live.setAttribute('aria-label','Open Food Facts search results');status.after(live);results.parentNode.insertBefore(samples,results);samples.append(results);var title=document.createElement('h2');title.textContent='Sample products';title.style.cssText='font-size:16px;margin:8px 0';samples.prepend(title);
var explainer=explore.querySelector('.card.sage');if(explainer){var h=explainer.querySelector('strong'),p=explainer.querySelector('p');if(h)h.textContent='Live search and sample products';if(p)p.textContent='Search uses community-contributed Open Food Facts records. Results may be incomplete or outdated; check the current package. Sample products below are illustrative.'}
function reset(){serial++;if(request){request.abort();request=null}submit.disabled=false;live.replaceChildren();samples.hidden=false;status.textContent='';last=''}
var deb=null;input.addEventListener('input',function(){if(input.value.trim()!==last)reset();clearTimeout(deb);var snap=input.value.trim().replace(/\s+/g,' ');if(snap.length<3)return;deb=setTimeout(function(){if(input.value.trim().replace(/\s+/g,' ')!==snap||snap===last)return;var wait=Math.max(0,until-Date.now());if(wait>0)status.textContent='Search queued. Open Food Facts limits how often we can search.';setTimeout(function(){if(input.value.trim().replace(/\s+/g,' ')!==snap||snap===last||request)return;if(form.requestSubmit)form.requestSubmit();else submit.click()},wait)},900)});
var sty=document.createElement('style');sty.textContent='.rcp-entry .grow>*,.lab-entry .grow>*{display:block}.rcp-entry small,.lab-entry small{color:var(--muted);margin-top:2px}';document.head.appendChild(sty);
function card(p){var b=document.createElement('button'),thumb=document.createElement('span'),main=document.createElement('span'),name=document.createElement('strong'),sub=document.createElement('small'),arrow=document.createElement('span');b.type='button';b.className='card asbutton row';b.style.cssText='width:100%;text-align:left;min-height:68px';thumb.className='thumb';thumb.setAttribute('aria-hidden','true');var img=p.image_front_small_url||p.image_small_url;if(img&&/^https:\/\//.test(img)){var im=document.createElement('img');im.src=img;im.alt='';im.loading='lazy';im.style.cssText='max-width:100%;max-height:100%;object-fit:contain';thumb.append(im)}else thumb.textContent='▣';main.className='grow';name.textContent=String(p.product_name_en||p.product_name||'Unnamed product');sub.textContent=(String(p.brands||'Brand not listed').split(',')[0].trim()||'Brand not listed')+(p.quantity?' · '+String(p.quantity).slice(0,24):'')+' · barcode ending '+String(p.code).slice(-4);main.append(name,sub);arrow.className='chevron';arrow.textContent='›';arrow.setAttribute('aria-hidden','true');b.append(thumb,main,arrow);b.addEventListener('click',function(){open(p.code)});return b}
async function open(code){var id=String(code||'');if(!/^\d{8,14}$/.test(id))return;serial++;if(request){request.abort();request=null}var scan=document.querySelector('[data-go="scan"]'),manual=document.getElementById('manualCode'),lookup=document.getElementById('lookupCode');if(!scan||!manual||!lookup){status.textContent='Product lookup is unavailable.';return}status.textContent='Opening product…';if(window.OLOpenCode){await window.OLOpenCode(id);status.textContent=''}else{scan.click();manual.value=id;lookup.click();status.textContent=''}}
form.addEventListener('submit',async function(e){e.preventDefault();var q=input.value.trim().replace(/\s+/g,' ');if(q.length<2){status.textContent='Enter at least two characters.';return}if(request)return;var key=q.toLowerCase();if(cache.has(key)){show(cache.get(key));last=q;return}if(Date.now()<until){status.textContent='Please wait a few seconds before searching again.';return}until=Date.now()+7000;last=q;var id=++serial,ctl=new AbortController(),timer=setTimeout(function(){ctl.abort()},12000);request=ctl;submit.disabled=true;live.replaceChildren();samples.hidden=true;status.textContent='Searching Open Food Facts…';try{var url='https://world.openfoodfacts.org/cgi/search.pl?search_terms='+encodeURIComponent(q)+'&search_simple=1&action=process&json=1&page_size=20&fields=code,quantity,product_name,product_name_en,brands,image_front_small_url,image_small_url';var response=await fetch(url,{signal:ctl.signal});if(!response.ok)throw new Error('Search failed');var data=await response.json();if(id!==serial)return;var items=Array.isArray(data.products)?data.products.filter(function(p){return p&&/^\d{8,14}$/.test(String(p.code||''))&&(p.product_name||p.product_name_en)}):[];cache.set(key,items);if(cache.size>12)cache.delete(cache.keys().next().value);show(items)}catch(err){if(id===serial){samples.hidden=false;status.textContent=err.name==='AbortError'?'Search timed out. Try again.':'Search unavailable. Check your connection and try again. This says nothing about whether the product exists. Sample products are below.'}}finally{clearTimeout(timer);if(request===ctl)request=null;if(id===serial)submit.disabled=false}});
function show(items){live.replaceChildren();samples.hidden=true;var seen={};items.forEach(function(p){var id=String(p.code);if(seen[id])return;seen[id]=true;live.append(card(p))});status.textContent=live.childElementCount?live.childElementCount+' live products found. Tap a product to open its details.':'No live products found. That does not mean the product is missing or unavailable. Try another name, or scan its barcode.'}
})();
