(function(){
'use strict';
var FDA_HIS='https://www.fda.gov/food/food-additives-petitions/high-intensity-sweeteners',FDA_SW='https://www.fda.gov/food/food-additives-petitions/aspartame-and-other-sweeteners-food',FDA_SAFE='https://www.fda.gov/consumers/consumer-updates/how-sweet-it-all-about-sweeteners',NIH_C='https://ods.od.nih.gov/factsheets/VitaminC-Consumer/',CFR='https://www.law.cornell.edu/cfr/text/21/101.22';
var FDA_GRAS='https://www.fda.gov/food/food-ingredients-packaging/generally-recognized-safe-gras',INV='https://hfpappexternal.fda.gov/scripts/fdcc/index.cfm?set=FoodSubstances&id=',ISAPP='https://isappscience.org/a-roundup-of-the-isapp-consensus-definitions-probiotics-prebiotics-synbiotics-postbiotics-and-fermented-foods/',FERMPM='https://pubmed.ncbi.nlm.nih.gov/33398112/',MICRO='https://pmc.ncbi.nlm.nih.gov/articles/PMC7986288/',AGA='https://news.gastro.org/issues/2026/april-2026/emulsifiers-found-to-lower-gut-metabolites-not-inflammation/',XANT='https://pmc.ncbi.nlm.nih.gov/articles/PMC7009887/',ECCALL='https://food.ec.europa.eu/food-safety/food-improvement-agents/additives/re-evaluation_en',LECEFSA='https://www.traceone.com/resources/plm-compliance-blog/efsa-opinion-on-re-evaluation-of-lecithins-e-322-as-a-food-additive-in-infant-foods-and-for-all-age-groups',ARS='https://agresearchmag.ars.usda.gov/2009/apr/caffeine';
var HIS_RULE='FDA treats high-intensity sweeteners as food additives unless they are generally recognized as safe. For the six it has approved, FDA concluded they are safe for the general population under certain conditions of use and set an acceptable daily intake for each.';
var SUGAR_ALC='Sugar alcohols are carbohydrates with some features of sugars and alcohols (not the kind of alcohol in drinks). The FDA says they are 25% to 100% as sweet as sugar, slightly lower in calories, and do not promote tooth decay or cause a sudden rise in blood glucose.';
var EMUL_FIND=['In a lab model using one healthy donor’s gut microbes, many of the 20 emulsifiers tested changed the microbes, including carboxymethylcellulose, polysorbate 80, carrageenans and several gums. Lecithin did not significantly. This was a lab model, not people.','The same research group reports that carboxymethylcellulose and polysorbate 80 promoted gut inflammation in mice.','In a randomized, placebo-controlled trial of 58 healthy adults in Belgium, four weeks of brownies containing one of five emulsifiers (carboxymethyl cellulose, polysorbate 80, carrageenan, soy lecithin or rice starch) lowered short-chain fatty acids made by gut microbes, but did not raise inflammation markers. The trial was small and short and tested single emulsifiers, not the mixtures in real foods.'];
var G=[
{keys:['steviol glycoside','stevia','e960'],name:'Stevia (steviol glycosides)',aka:'Steviol glycosides, stevia leaf extract, stevia rebaudiana extract, E960',what:'A sweetener extracted from the leaves of the stevia plant. Products usually use highly purified steviol glycosides.',why:'It is many times sweeter than table sugar, so only a little is needed and it adds few or no calories.',reg:'The FDA has not questioned the safety conclusions that companies submitted for highly purified steviol glycosides. Whole-leaf and crude stevia extracts are not permitted as sweeteners in the US. The FAO/WHO expert committee (JECFA) set an acceptable daily intake.',src:[['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['sucralose','e955'],name:'Sucralose',aka:'E955',what:'A high-intensity sweetener.',why:'It is many times sweeter than table sugar and adds few or no calories.',reg:'Sucralose is one of six high-intensity sweeteners the FDA has approved as food additives (with saccharin, aspartame, acesulfame potassium, neotame and advantame). '+HIS_RULE,src:[['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['aspartame','e951'],name:'Aspartame',aka:'E951, brand names such as NutraSweet and Equal',what:'A high-intensity sweetener first approved by the FDA in 1974.',why:'It is many times sweeter than table sugar and adds few or no calories.',reg:'The FDA says scientific evidence continues to support its conclusion that aspartame is safe for the general population when used under the approved conditions. People with phenylketonuria (PKU) should avoid or limit it, and products with aspartame must carry a statement about phenylalanine.',src:[['FDA: Aspartame and other sweeteners in food',FDA_SW],['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['acesulfame','ace-k','e950'],name:'Acesulfame potassium (Ace-K)',aka:'Acesulfame K, E950',what:'A high-intensity sweetener first approved by the FDA in 1988.',why:'It is many times sweeter than table sugar and adds few or no calories.',reg:'Ace-K is one of six high-intensity sweeteners approved as food additives. '+HIS_RULE,src:[['FDA: How sweet it is',FDA_SAFE],['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['saccharin','e954'],name:'Saccharin',aka:'E954',what:'A high-intensity sweetener.',why:'It is many times sweeter than table sugar and adds few or no calories.',reg:'Saccharin is one of six high-intensity sweeteners approved as food additives. '+HIS_RULE,src:[['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['erythritol','e968'],name:'Erythritol',aka:'E968',what:'A sugar alcohol used as a sugar substitute.',why:'It sweetens with fewer calories than sugar and is used mainly in sugar-free candies, cookies and chewing gum.',reg:SUGAR_ALC+' In 2023 the FDA reviewed a scientific paper on possible heart and blood vessel effects of erythritol and said the observational studies it cited did not establish a causal link.',src:[['FDA: Aspartame and other sweeteners in food',FDA_SW]]},
{keys:['xylitol','e967'],name:'Xylitol',aka:'E967',what:'A sugar alcohol used as a sugar substitute.',why:'It sweetens with fewer calories than sugar and is used mainly in sugar-free candies, cookies and chewing gum.',reg:SUGAR_ALC,src:[['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['monk fruit','luo han guo'],name:'Monk fruit extract',aka:'Luo han guo, Siraitia grosvenorii extract',what:'A sweetener extracted from the monk fruit (Siraitia grosvenorii).',why:'It is many times sweeter than table sugar and adds few or no calories.',reg:'Companies have submitted safety conclusions to the FDA for monk fruit extracts, and the FDA has not questioned them for the intended uses described. No acceptable daily intake has been specified for monk fruit.',src:[['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['natural flavor','natural flavour'],name:'Natural flavors',aka:'Natural flavoring',what:'A flavoring made from a natural source such as a spice, fruit, vegetable, herb, meat, seafood, dairy product or yeast, or from a product of roasting, heating or fermenting them.',why:'It is added for flavor, not nutrition. Under US rules, a natural flavor is one whose main job in food is flavoring.',reg:'This is the definition in US food labeling rules (21 CFR 101.22). Labels may list it simply as natural flavor, so the ingredient list does not show the individual components.',src:[['US rules: 21 CFR 101.22',CFR]]},
{keys:['ascorbic acid','vitamin c','e300'],name:'Ascorbic acid (vitamin C)',aka:'Vitamin C, L-ascorbic acid, E300',what:'Vitamin C, a water-soluble nutrient found naturally in fruits and vegetables and added to some foods and drinks.',why:'Food makers add it to some products, either as a nutrient or to help keep food fresh. When it is added as a preservative, US rules require the label to say what it does.',reg:'The NIH says taking too much vitamin C can cause diarrhea, nausea and stomach cramps, and sets an upper limit of 2,000 mg a day for adults from all sources.',src:[['NIH: Vitamin C fact sheet',NIH_C],['US rules: 21 CFR 101.22',CFR]]},
{keys:['sunflower','safflower','canola','rapeseed','soybean','soya','corn oil','cottonseed','grapeseed','rice bran'],name:'Seed oil',aka:'Sunflower, safflower, canola (rapeseed), soybean, corn, cottonseed, grapeseed and rice bran oils',what:'An oil extracted from the seeds or grains of a plant. The term seed oil is informal, and lists of which oils count vary.',why:'Used as a cooking oil and as an ingredient in processed foods.',reg:'Claims about seed oils are common online and the research is mixed. We show both sides and who paid for the studies in our evidence summary.',evidence:true,src:[]},
{keys:['citric acid','e330'],name:'Citric acid',aka:'E330',what:'An acid used in foods and drinks. It is found naturally in citrus fruits.',why:'The FDA lists its technical effects as including pH control, flavoring, antioxidant, sequestrant (it binds metals) and antimicrobial agent, among others.',reg:'Citric acid is listed in FDA’s inventory of substances added to food, including in 21 CFR 184.1033, a regulation for substances affirmed as generally recognized as safe (GRAS).',src:[['FDA: Substances added to food, citric acid',INV+'CITRICACID'],['FDA: What GRAS means',FDA_GRAS]]},
{keys:['sodium benzoate','e211'],name:'Sodium benzoate',aka:'E211, benzoic acid sodium salt',what:'A preservative, the sodium salt of benzoic acid.',why:'The FDA lists its technical effects as including antimicrobial agent, antioxidant, flavoring and pH control.',reg:'Sodium benzoate is listed in FDA’s inventory of substances added to food under 21 CFR 181.23 (prior sanctioned ingredients) and 21 CFR 184.1733 (affirmed GRAS).',src:[['FDA: Substances added to food, sodium benzoate',INV+'SODIUMBENZOATE'],['FDA: What GRAS means',FDA_GRAS]]},
{keys:['potassium sorbate','e202'],name:'Potassium sorbate',aka:'E202, sorbic acid potassium salt',what:'A preservative, the potassium salt of sorbic acid.',why:'The FDA lists its technical effects as including antimicrobial agent, antioxidant, flavoring and pH control.',reg:'Potassium sorbate is listed in FDA’s inventory of substances added to food under 21 CFR 182.3640 and 182.90, regulations for substances generally recognized as safe (GRAS).',src:[['FDA: Substances added to food, potassium sorbate',INV+'POTASSIUMSORBATE'],['FDA: What GRAS means',FDA_GRAS]]},
{keys:['xanthan gum','e415'],name:'Xanthan gum',aka:'E415',what:'A gum used to thicken and stabilize foods. Researchers who study the gut sometimes group it with emulsifiers.',why:'It keeps sauces, dressings, drinks and gluten-free baked goods smooth and stops ingredients separating.',reg:'In 2017 the European Food Safety Authority (EFSA) concluded there was no need for a numerical acceptable daily intake and no safety concern at the reported uses. A later EFSA review of its use in special medical foods for infants found no safety concern there either.',st:'Not yet reviewed by us',src:[['EFSA re-evaluation of xanthan gum (2017)',XANT]]},
{keys:['carrageenan','e407'],name:'Carrageenan',aka:'E407',what:'A thickener and gelling agent made from red seaweed.',why:'It is used to thicken and stabilize foods such as dairy products, plant milks and deli meats.',reg:'EFSA re-evaluated carrageenan (E 407) in 2018. The European Commission later asked for more safety data on its use in foods for infants under 16 weeks old.',find:['Carrageenan was one of the emulsifying additives tested in the gut research described under Emulsifiers. Evidence on additives like it is mixed.'],st:'Mixed evidence',src:[['European Commission: re-evaluation of food additives',ECCALL],['Lab study (Microbiome, 2021)',MICRO]]},
{keys:['soy lecithin','sunflower lecithin','lecithin','e322'],name:'Lecithin',aka:'E322, soy lecithin, sunflower lecithin',what:'A fat-based substance used as an emulsifier, usually made from soy or sunflower.',why:'It helps oil and water mix, and keeps chocolate, baked goods and spreads smooth.',reg:'EFSA concluded that lecithins used as a food additive in infant formula and in special medical foods do not raise safety concerns up to the maximum permitted level.',find:['In the 2021 lab model of human gut microbes, lecithin did not significantly change the microbes, unlike several other emulsifiers.','Soy lecithin was one of five emulsifiers in a four-week randomized trial in 58 healthy adults. Across the five, gut-microbe byproducts fell but inflammation markers did not rise.'],st:'Mixed evidence',src:[['EFSA opinion on lecithins (summary)',LECEFSA],['Lab study (Microbiome, 2021)',MICRO],['Trial report (AGA, April 2026)',AGA]]},
{keys:['emulsifier','polysorbate','carboxymethylcellulose','cellulose gum','mono- and diglycerides','mono and diglycerides','monoglycerides','diglycerides'],name:'Emulsifiers and stabilizers',aka:'Includes polysorbate 80, carboxymethylcellulose (cellulose gum), mono- and diglycerides, lecithin, carrageenan and gums',what:'Additives that help oil and water mix, or that thicken and stabilize a food. Researchers group several gums and thickeners with emulsifiers.',why:'They improve texture and extend shelf life.',reg:'Each additive has its own regulatory status. See the entries for lecithin, xanthan gum and carrageenan.',find:EMUL_FIND,st:'Mixed evidence',src:[['Lab study (Microbiome, 2021)',MICRO],['Trial report (AGA, April 2026)',AGA]]},
{keys:['live and active cultures','live cultures','active cultures','probiotic','lactobacillus','bifidobacterium'],name:'Probiotics and live cultures',aka:'Live and active cultures, Lactobacillus, Bifidobacterium',what:'Scientists define a probiotic as live microorganisms that, when given in adequate amounts, give a health benefit.',why:'They are added to yogurt, drinks and supplements, often with gut-health claims.',reg:'A label that says live cultures does not tell us the strain or the amount. Under the scientific definition, a product only counts as a probiotic if its microbes give a benefit, and that is judged for the specific microbe and amount.',st:'Not yet reviewed by us',src:[['ISAPP: consensus definitions',ISAPP]]},
{keys:['prebiotic','inulin','chicory root','chicory fiber','fructooligosaccharides','oligofructose'],name:'Prebiotics and prebiotic fibers',aka:'Inulin, chicory root fiber, fructooligosaccharides, oligofructose',what:'Scientists define a prebiotic as a substrate that gut microbes selectively use to give a health benefit. They treat it as distinct from fiber in general.',why:'Inulin and chicory root fiber are plant fibers sometimes added to foods and marketed as prebiotics.',reg:'The label word prebiotic or an ingredient like inulin does not show that a health benefit has been demonstrated for that product.',st:'Not yet reviewed by us',src:[['ISAPP: consensus definitions',ISAPP]]},
{keys:['fermented','kefir','kombucha','kimchi','sauerkraut','tempeh','natto','sourdough','yogurt','yoghurt'],name:'Fermented foods',aka:'Yogurt, kefir, kombucha, kimchi, sauerkraut, miso, tempeh, natto, sourdough',what:'Scientists define fermented foods as foods made through desired microbial growth and enzymatic conversion of food components.',why:'Fermenting changes flavor and texture and helps preserve the food.',reg:'A fermented food is not the same as a probiotic. It need not contain live microbes, and it is not shown to give a health benefit just because it is fermented.',st:'Not yet reviewed by us',src:[['ISAPP consensus statement on fermented foods',FERMPM],['ISAPP: consensus definitions',ISAPP]]},
{keys:['caffeine','guarana','yerba mate','kola nut','cola nut','green tea extract','tea extract','matcha'],name:'Caffeine and caffeine sources',aka:'Guarana, yerba mate, kola nut, green tea and tea extracts',what:'Caffeine is a stimulant. Besides added caffeine, plant ingredients like guarana, yerba mate, kola nut and tea extracts can contain it.',why:'It is added to drinks, bars and supplements for a stimulant effect.',reg:'In the US there is no requirement to state the amount of caffeine in a food, and plant ingredients that contain caffeine may not be labeled as caffeine sources. We have not yet summarized caffeine’s health effects.',st:'Not yet reviewed by us',src:[['USDA Agricultural Research Service: caffeine in botanicals',ARS]]}
];
var TERMS=[];G.forEach(function(g){g.keys.forEach(function(k){if(k.length>=5&&TERMS.indexOf(k)<0)TERMS.push(k)})});
var sty=document.createElement('style');
sty.textContent='#olPanel .ing mark,#olPanel .chiprow span{cursor:pointer;text-decoration:underline dotted;text-underline-offset:3px}#olPanel .ing mark.m-gl{background:none}#olPanel .ing mark:focus-visible,#olPanel .chiprow span:focus-visible{outline:3px solid var(--eucalyptus);outline-offset:2px}.gl h4{font-size:11px;letter-spacing:.11em;text-transform:uppercase;color:var(--eucalyptus);margin:14px 0 4px}.gl p{margin:0;color:var(--ink);font-size:14px}.gl ul{margin:0;padding-left:18px;color:var(--ink);font-size:14px}.gl li{margin:4px 0}.gl .gl-st{display:inline-block;border-radius:99px;padding:5px 11px;background:#ECEFED;color:#4B5651;font-size:12px;font-weight:780}.gl .gl-st.mx{background:#F8F0C6;color:#675300}.gl a{color:var(--forest);font-weight:700;overflow-wrap:anywhere}.gl .gl-b{background:none;color:var(--forest);font-weight:760;padding:8px 0;font-size:14px}.gl-link{background:none;color:var(--forest);font-weight:760;padding:6px 0;font-size:14px;display:block}';
document.head.appendChild(sty);
function el(t,c,x){var e=document.createElement(t);if(c)e.className=c;if(x!=null)e.textContent=x;return e}
function lookup(txt){var t=String(txt||'').toLowerCase(),best=null,bl=0;G.forEach(function(g){g.keys.forEach(function(k){if(t.indexOf(k)>=0&&k.length>bl){best=g;bl=k.length}})});return best}
function sec(root,h,body){root.append(el('h4',null,h));root.append(typeof body==='string'?el('p',null,body):body)}
function open(txt){var g=lookup(txt),root=el('div','gl'),title,intro;
if(g){title=g.name;intro=g.aka?'Also listed as: '+g.aka+'.':'';sec(root,'What it is',g.what);sec(root,'Why it is used',g.why);sec(root,'What regulators say',g.reg);
if(g.find){var ul=el('ul');g.find.forEach(function(f){ul.append(el('li',null,f))});sec(root,'What we found',ul)}
var st=el('div');if(g.evidence&&window.OLEvidence&&window.OLEvidence.api){st.append(el('span','gl-st mx','Contested evidence'));var b=el('button','gl-b','See the seed oil evidence');b.onclick=function(){window.OLEvidence.api.openSeedSheet([String(txt).toLowerCase()],false)};st.append(document.createElement('br'),b)}
else if(g.st){st.append(el('span','gl-st'+(/mixed/i.test(g.st)?' mx':''),g.st))}
else st.append(el('span','gl-st','OpenLabel has not reviewed the research on this yet'));sec(root,'Our review',st);
if(g.src.length){var p=el('p');g.src.forEach(function(s,i){if(i)p.append(document.createElement('br'));var a=el('a',null,s[0]);a.href=s[1];a.target='_blank';a.rel='noopener noreferrer';p.append(a)});sec(root,'Sources',p)}}
else{title=String(txt).trim();intro='We do not have a description for this ingredient yet.';sec(root,'Our review',el('p',null,'OpenLabel has not reviewed this ingredient. Listed does not mean harmful, and not described does not mean safe. Check the package.'))}
var tt=document.getElementById('sheetTitle'),cc=document.getElementById('sheetContent'),ex=document.getElementById('sheetExtra'),w=document.getElementById('sheetWrap');if(!tt||!cc||!ex||!w)return;
tt.textContent=title;cc.textContent=intro;ex.replaceChildren(root);w.hidden=false;var cs=document.getElementById('closeSheet');if(cs)cs.focus()}
document.addEventListener('click',function(e){var t=e.target.closest&&e.target.closest('#olPanel .ing mark, #olPanel .chiprow span');if(!t)return;open(t.textContent)});
document.addEventListener('keydown',function(e){if(e.key!=='Enter'&&e.key!==' ')return;var t=e.target;if(t&&t.matches&&t.matches('#olPanel .ing mark, #olPanel .chiprow span')){e.preventDefault();open(t.textContent)}});
function wrapNode(n){var txt=n.nodeValue,low=txt.toLowerCase(),best=null,bi=1e9;TERMS.forEach(function(t){var i=low.indexOf(t);if(i>=0&&(i<bi||(i===bi&&(!best||t.length>best.length)))){bi=i;best=t}});if(!best)return;var f=document.createDocumentFragment(),mk=document.createElement('mark'),rest;f.append(txt.slice(0,bi));mk.className='m-gl';mk.textContent=txt.slice(bi,bi+best.length);f.append(mk);rest=document.createTextNode(txt.slice(bi+best.length));f.append(rest);n.replaceWith(f);wrapNode(rest)}
function wrapIng(root){var w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,null),nodes=[],n;while((n=w.nextNode())){if(n.parentNode.nodeName!=='MARK')nodes.push(n)}nodes.forEach(wrapNode)}
var LINKS={'Emulsifiers and stabilizers':[['What are emulsifiers?','emulsifier']],'Gut: live cultures, prebiotics, fermented':[['What is a probiotic?','probiotic'],['What is a prebiotic?','prebiotic'],['What is a fermented food?','fermented']],'Caffeine':[['About caffeine sources','caffeine']]};
var busy=false;
function decorate(){if(busy)return;busy=true;try{[].forEach.call(document.querySelectorAll('#olPanel .ing'),wrapIng);
[].forEach.call(document.querySelectorAll('#olPanel .ing mark, #olPanel .chiprow span'),function(n){if(!n.hasAttribute('tabindex')){n.setAttribute('tabindex','0');n.setAttribute('role','button');n.setAttribute('aria-label','About '+n.textContent)}});
[].forEach.call(document.querySelectorAll('#olPanel .ingcard'),function(c){if(c.querySelector('mark')&&!c.querySelector('.gl-hint')){c.append(el('p','olp-note gl-hint','Tap a highlighted word to see what it is.'))}});
[].forEach.call(document.querySelectorAll('#olPanel details.olr'),function(d){var t=d.querySelector('.t'),k=t&&LINKS[t.textContent.trim()],b=d.querySelector('.olr-b');if(!k||!b||b.querySelector('.gl-link'))return;k.forEach(function(l){var bt=el('button','gl-link',l[0]);bt.onclick=function(){open(l[1])};b.append(bt)})});}finally{busy=false}}
new MutationObserver(function(){decorate()}).observe(document.body,{childList:true,subtree:true});
decorate();
window.OLGloss={open:open,lookup:lookup};
})();
