(function(){
'use strict';
var FDA_HIS='https://www.fda.gov/food/food-additives-petitions/high-intensity-sweeteners',FDA_SW='https://www.fda.gov/food/food-additives-petitions/aspartame-and-other-sweeteners-food',FDA_SAFE='https://www.fda.gov/consumers/consumer-updates/how-sweet-it-all-about-sweeteners',NIH_C='https://ods.od.nih.gov/factsheets/VitaminC-Consumer/',CFR='https://www.law.cornell.edu/cfr/text/21/101.22';
var HIS_RULE='FDA treats high-intensity sweeteners as food additives unless they are generally recognized as safe. For the six it has approved, FDA concluded they are safe for the general population under certain conditions of use and set an acceptable daily intake for each.';
var SUGAR_ALC='Sugar alcohols are carbohydrates with some features of sugars and alcohols (not the kind of alcohol in drinks). The FDA says they are 25% to 100% as sweet as sugar, slightly lower in calories, and do not promote tooth decay or cause a sudden rise in blood glucose.';
var G=[
{keys:['steviol glycoside','stevia','e960'],name:'Stevia (steviol glycosides)',aka:'Steviol glycosides, stevia leaf extract, stevia rebaudiana extract, E960',what:'A sweetener extracted from the leaves of the stevia plant. Products usually use highly purified steviol glycosides.',why:'It is many times sweeter than table sugar, so only a little is needed and it adds few or no calories.',reg:'The FDA has not questioned the safety conclusions that companies submitted for highly purified steviol glycosides. Whole-leaf and crude stevia extracts are not permitted as sweeteners in the US. The FAO/WHO expert committee (JECFA) set an acceptable daily intake.',src:[['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['sucralose','e955'],name:'Sucralose',aka:'E955',what:'A high-intensity sweetener.',why:'It is many times sweeter than table sugar and adds few or no calories.',reg:'Sucralose is one of six high-intensity sweeteners the FDA has approved as food additives (with saccharin, aspartame, acesulfame potassium, neotame and advantame). '+HIS_RULE,src:[['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['aspartame','e951'],name:'Aspartame',aka:'E951, brand names such as NutraSweet and Equal',what:'A high-intensity sweetener first approved by the FDA in 1974.',why:'It is many times sweeter than table sugar and adds few or no calories.',reg:'The FDA says scientific evidence continues to support its conclusion that aspartame is safe for the general population when used under the approved conditions. People with phenylketonuria (PKU) should avoid or limit it, and products with aspartame must carry a statement about phenylalanine.',src:[['FDA: Aspartame and other sweeteners in food',FDA_SW],['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['acesulfame','ace-k','e950'],name:'Acesulfame potassium (Ace-K)',aka:'Acesulfame K, E950',what:'A high-intensity sweetener first approved by the FDA in 1988.',why:'It is many times sweeter than table sugar and adds few or no calories.',reg:'Ace-K is one of six high-intensity sweeteners approved as food additives. '+HIS_RULE,src:[['FDA: How sweet it is',FDA_SAFE],['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['saccharin','e954'],name:'Saccharin',aka:'E954',what:'A high-intensity sweetener.',why:'It is many times sweeter than table sugar and adds few or no calories.',reg:'Saccharin is one of six high-intensity sweeteners approved as food additives. '+HIS_RULE,src:[['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['erythritol','e968'],name:'Erythritol',aka:'E968',what:'A sugar alcohol used as a sugar substitute.',why:'It sweetens with fewer calories than sugar and is used mainly in sugar-free candies, cookies and chewing gum.',reg:SUGAR_ALC+' In 2023 the FDA reviewed a scientific paper on possible heart and blood vessel effects of erythritol and said the observational studies it cited did not establish a causal link.',src:[['FDA: Aspartame and other sweeteners in food',FDA_SW]]},
{keys:['xylitol','e967'],name:'Xylitol',aka:'E967',what:'A sugar alcohol used as a sugar substitute.',why:'It sweetens with fewer calories than sugar and is used mainly in sugar-free candies, cookies and chewing gum.',reg:SUGAR_ALC,src:[['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['monk fruit','luo han guo'],name:'Monk fruit extract',aka:'Luo han guo, Siraitia grosvenorii extract',what:'A sweetener extracted from the monk fruit (Siraitia grosvenorii).',why:'It is many times sweeter than table sugar and adds few or no calories.',reg:'Companies have submitted safety conclusions to the FDA for monk fruit extracts, and the FDA has not questioned them for the intended uses described. No acceptable daily intake has been specified for monk fruit.',src:[['FDA: High-intensity sweeteners',FDA_HIS]]},
{keys:['natural flavor','natural flavour'],name:'Natural flavors',aka:'Natural flavoring',what:'A flavoring made from a natural source such as a spice, fruit, vegetable, herb, meat, seafood, dairy product or yeast, or from a product of roasting, heating or fermenting them.',why:'It is added for flavor, not nutrition. Under US rules, a natural flavor is one whose main job in food is flavoring.',reg:'This is the definition in US food labeling rules (21 CFR 101.22). Labels may list it simply as natural flavor, so the ingredient list does not show the individual components.',src:[['US rules: 21 CFR 101.22',CFR]]},
{keys:['ascorbic acid','vitamin c','e300'],name:'Ascorbic acid (vitamin C)',aka:'Vitamin C, L-ascorbic acid, E300',what:'Vitamin C, a water-soluble nutrient found naturally in fruits and vegetables and added to some foods and drinks.',why:'Food makers add it to some products, either as a nutrient or to help keep food fresh. When it is added as a preservative, US rules require the label to say what it does.',reg:'The NIH says taking too much vitamin C can cause diarrhea, nausea and stomach cramps, and sets an upper limit of 2,000 mg a day for adults from all sources.',src:[['NIH: Vitamin C fact sheet',NIH_C],['US rules: 21 CFR 101.22',CFR]]},
{keys:['sunflower','safflower','canola','rapeseed','soybean','soya','corn oil','cottonseed','grapeseed','rice bran'],name:'Seed oil',aka:'Sunflower, safflower, canola (rapeseed), soybean, corn, cottonseed, grapeseed and rice bran oils',what:'An oil extracted from the seeds or grains of a plant. The term seed oil is informal, and lists of which oils count vary.',why:'Used as a cooking oil and as an ingredient in processed foods.',reg:'Claims about seed oils are common online and the research is mixed. We show both sides and who paid for the studies in our evidence summary.',evidence:true,src:[]}
];
var sty=document.createElement('style');
sty.textContent='#olPanel .ing mark,#olPanel .chiprow span{cursor:pointer;text-decoration:underline dotted;text-underline-offset:3px}#olPanel .ing mark:focus-visible,#olPanel .chiprow span:focus-visible{outline:3px solid var(--eucalyptus);outline-offset:2px}.gl h4{font-size:11px;letter-spacing:.11em;text-transform:uppercase;color:var(--eucalyptus);margin:14px 0 4px}.gl p{margin:0;color:var(--ink);font-size:14px}.gl .gl-st{display:inline-block;border-radius:99px;padding:5px 11px;background:#ECEFED;color:#4B5651;font-size:12px;font-weight:780}.gl a{color:var(--forest);font-weight:700;overflow-wrap:anywhere}.gl .gl-b{background:none;color:var(--forest);font-weight:760;padding:8px 0;font-size:14px}';
document.head.appendChild(sty);
function el(t,c,x){var e=document.createElement(t);if(c)e.className=c;if(x!=null)e.textContent=x;return e}
function lookup(txt){var t=String(txt||'').toLowerCase(),best=null,bl=0;G.forEach(function(g){g.keys.forEach(function(k){if(t.indexOf(k)>=0&&k.length>bl){best=g;bl=k.length}})});return best}
function sec(root,h,body){root.append(el('h4',null,h));root.append(typeof body==='string'?el('p',null,body):body)}
function open(txt){var g=lookup(txt),root=el('div','gl'),title,intro;
if(g){title=g.name;intro=g.aka?'Also listed as: '+g.aka+'.':'';sec(root,'What it is',g.what);sec(root,'Why it is used',g.why);sec(root,'What regulators say',g.reg);
var st=el('div');if(g.evidence&&window.OLEvidence&&window.OLEvidence.api){st.append(el('span','gl-st','Contested evidence'));var b=el('button','gl-b','See the seed oil evidence');b.onclick=function(){window.OLEvidence.api.openSeedSheet([String(txt).toLowerCase()],false)};st.append(document.createElement('br'),b)}
else st.append(el('span','gl-st','OpenLabel has not reviewed the research on this yet'));sec(root,'Our review',st);
if(g.src.length){var p=el('p');g.src.forEach(function(s,i){if(i)p.append(document.createElement('br'));var a=el('a',null,s[0]);a.href=s[1];a.target='_blank';a.rel='noopener noreferrer';p.append(a)});sec(root,'Sources',p)}}
else{title=String(txt).trim();intro='We do not have a description for this ingredient yet.';sec(root,'Our review',el('p',null,'OpenLabel has not reviewed this ingredient. Listed does not mean harmful, and not described does not mean safe. Check the package.'))}
var tt=document.getElementById('sheetTitle'),cc=document.getElementById('sheetContent'),ex=document.getElementById('sheetExtra'),w=document.getElementById('sheetWrap');if(!tt||!cc||!ex||!w)return;
tt.textContent=title;cc.textContent=intro;ex.replaceChildren(root);w.hidden=false;var cs=document.getElementById('closeSheet');if(cs)cs.focus()}
document.addEventListener('click',function(e){var t=e.target.closest&&e.target.closest('#olPanel .ing mark, #olPanel .chiprow span');if(!t)return;open(t.textContent)});
document.addEventListener('keydown',function(e){if(e.key!=='Enter'&&e.key!==' ')return;var t=e.target;if(t&&t.matches&&t.matches('#olPanel .ing mark, #olPanel .chiprow span')){e.preventDefault();open(t.textContent)}});
var busy=false;
function decorate(){if(busy)return;busy=true;try{[].forEach.call(document.querySelectorAll('#olPanel .ing mark, #olPanel .chiprow span'),function(n){if(!n.hasAttribute('tabindex')){n.setAttribute('tabindex','0');n.setAttribute('role','button');n.setAttribute('aria-label','About '+n.textContent)}});
[].forEach.call(document.querySelectorAll('#olPanel .ingcard'),function(c){if(c.querySelector('mark')&&!c.querySelector('.gl-hint')){c.append(el('p','olp-note gl-hint','Tap a highlighted word to see what it is.'))}})}finally{busy=false}}
new MutationObserver(function(){decorate()}).observe(document.body,{childList:true,subtree:true});
decorate();
window.OLGloss={open:open,lookup:lookup};
})();
