(function(){'use strict';
var O='https://ods.od.nih.gov/factsheets/';
var refs={b12:O+'VitaminB12-HealthProfessional/',d:O+'VitaminD-HealthProfessional/',folate:O+'Folate-HealthProfessional/',mg:O+'Magnesium-HealthProfessional/',e:O+'VitaminE-HealthProfessional/'};
var entries=[
{re:/^cyanocobalamin$/i,role:'Vitamin B12 form',form:'Cyanocobalamin is the form named on this label. It is a manufactured form of B12; the body converts it to active B12 forms.',difference:'NIH reports no evidence that absorption of supplemental B12 differs by form. A different-sounding form is not automatically better.',source:refs.b12},
{re:/^(methylcobalamin|hydroxocobalamin|hydroxycobalamin|adenosylcobalamin)$/i,role:'Vitamin B12 form',form:'The label names this B12 form. Methylcobalamin and adenosylcobalamin are metabolically active forms; hydroxocobalamin is converted in the body.',difference:'NIH reports no evidence that absorption of supplemental B12 differs by form. The label does not establish how this ingredient was manufactured.',source:refs.b12},
{re:/^(vitamin b12|cobalamin)$/i,role:'Vitamin B12 · form not specified',form:'The label does not name which B12 compound is used. We cannot determine whether it is cyanocobalamin, methylcobalamin, or another form.',difference:'NIH describes multiple B12 forms; it reports no evidence of differing absorption rates among supplemental forms.',source:refs.b12},
{re:/^(ergocalciferol|vitamin d2)$/i,role:'Vitamin D2 form',form:'This label names ergocalciferol (D2). The raw material and manufacturing process for this product are not given.',difference:'Both D2 and D3 raise vitamin D blood levels; D3 generally raises them more and maintains them longer at comparable doses.',source:refs.d},
{re:/^(cholecalciferol|vitamin d3)$/i,role:'Vitamin D3 form',form:'This label names cholecalciferol (D3). D3 can come from animal-derived lanolin or animal-free lichen; the label alone does not identify this product’s source.',difference:'Both D2 and D3 raise vitamin D blood levels; D3 generally raises them more and maintains them longer at comparable doses.',source:refs.d},
{re:/^vitamin d$/i,role:'Vitamin D · form not specified',form:'The label does not say whether this is D2 or D3, or where it came from.',difference:'D2 and D3 both raise blood vitamin D; D3 generally raises it more and for longer at comparable doses.',source:refs.d},
{re:/^folic acid$/i,role:'Folate form',form:'Folic acid is the manufactured, fully oxidized form of folate used in fortified foods and many supplements.',difference:'It differs chemically from food folates and 5-MTHF. In pregnancy, do not replace folic-acid guidance based on an ingredient name alone.',source:refs.folate},
{re:/^(?:l-)?(?:5-)?methylfolate|5-mthf|l-5-mthf|levomefolate(?: calcium)?$/i,role:'Folate form',form:'The label names a 5-MTHF/methylfolate form rather than folic acid. It does not establish its source or the dose absorbed from this product.',difference:'NIH says supplemental 5-MTHF is at least as bioavailable as folic acid, but pregnancy guidance still specifically recommends folic acid.',source:refs.folate},
{re:/^(folate|vitamin b9)$/i,role:'Folate · form not specified',form:'This wording does not identify whether the ingredient is folic acid, 5-MTHF, or another folate form.',difference:'Forms and labeling conventions differ. Do not infer a specific form from the vitamin name alone.',source:refs.folate},
{re:/^magnesium (oxide|citrate|chloride|lactate|aspartate|sulfate)$/i,role:'Magnesium form',form:'The magnesium compound is named on the label. The label alone does not tell us how much elemental magnesium comes from this ingredient.',difference:'Small studies summarized by NIH found citrate, chloride, lactate and aspartate generally better absorbed than oxide and sulfate. This does not establish a clinical outcome for this product.',source:refs.mg},
{re:/^magnesium$/i,role:'Magnesium · form not specified',form:'The label does not name the magnesium compound, so its form and relative absorption cannot be identified.',difference:'Different magnesium forms can differ in absorption; the product amount and context also matter.',source:refs.mg},
{re:/^(d-|dl-)?alpha[- ]tocopher(?:ol|yl acetate|yl succinate)$/i,role:'Vitamin E form',form:'The label names an alpha-tocopherol form. d-alpha generally denotes naturally sourced vitamin E; dl-alpha denotes a manufactured mixture. If neither prefix appears, the source is not established.',difference:'NIH describes different vitamin E activity by weight for natural and synthetic alpha-tocopherol. This alone is not a safety verdict.',source:refs.e},
{re:/^(vitamin e|mixed tocopherols)$/i,role:'Vitamin E · form not fully specified',form:'Vitamin E refers to multiple compounds; this wording does not identify the full composition or source of this product’s vitamin E.',difference:'NIH distinguishes alpha-tocopherol from other tocopherols and naturally sourced from synthetic alpha-tocopherol.',source:refs.e}
];
function split(text){var out=[],buf='',depth=0;for(var i=0;i<text.length;i++){var c=text[i];if(c==='('||c==='[')depth++;if(c===')'||c===']')depth=Math.max(0,depth-1);if((c===','||c===';')&&depth===0){if(buf.trim())out.push(buf.trim());buf='';}else buf+=c;}if(buf.trim())out.push(buf.trim());return out;}
function normalize(t){return t.trim().replace(/^[.\s]+|[.\s]+$/g,'').replace(/^(?:ingredients?\s*:\s*)/i,'').replace(/^(?:contains?\s+2%\s+or\s+less\s+of\s*:\s*)/i,'').trim()}
function match(t){var n=normalize(t);for(var i=0;i<entries.length;i++)if(entries[i].re.test(n))return entries[i];return null}
function make(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n}
var sheet=null,previous=null;function close(){if(!sheet)return;sheet.remove();sheet=null;document.body.classList.remove('ol-ing-open');if(previous&&document.contains(previous))previous.focus();previous=null}
function field(parent,title,text){parent.append(make('h4','ol-ing-label',title),make('p','',text))}
function open(label,context){close();previous=document.activeElement;var e=match(label),overlay=make('div','ol-ing-overlay');sheet=overlay;overlay.setAttribute('role','presentation');var box=make('section','ol-ing-sheet');box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-label','Ingredient: '+label);var x=make('button','ol-ing-close','×');x.type='button';x.setAttribute('aria-label','Close ingredient information');x.onclick=close;box.append(x,make('h3','',label),make('p','ol-ing-role',e?e.role:'Not yet reviewed'));if(context)box.append(make('p','ol-ing-context',context));field(box,'Label says',label);if(e){field(box,'Form and origin',e.form);field(box,'What research says',e.difference);var a=make('a','ol-ing-source','Read NIH Office of Dietary Supplements');a.href=e.source;a.target='_blank';a.rel='noopener noreferrer';box.append(a)}else{field(box,'What we know','We have not reviewed this exact ingredient yet. Its name alone does not establish its purpose, source, effects, or safety.');field(box,'Form and origin','Not verified from this label. Check the package or ask the manufacturer for specifics.')}field(box,'Still unknown','The label text alone does not establish the ingredient’s dose, manufacturing process, or effects for an individual. This is not a product safety assessment.');overlay.append(box);document.body.append(overlay);overlay.onclick=function(ev){if(ev.target===overlay)close()};x.focus()}
function row(label,context){var b=make('button','ol-ing-row');b.type='button';b.append(make('span','ol-ing-row-name',label),make('span','ol-ing-row-meta',(match(label)?match(label).role:'Not yet reviewed')+'  ›'));b.onclick=function(){open(label,context)};return b}
function render(text){var root=make('div','ol-ing-explore');var chunks=split(text),list=make('div','ol-ing-list');if(!chunks.length){root.append(make('p','','No ingredient list is available for this product.'));return root}root.append(make('p','ol-ing-intro','Tap an ingredient to see what the label tells us—and what it doesn’t.'));chunks.forEach(function(raw){var s=raw.trim(),idx=s.indexOf('('),end=s.lastIndexOf(')');if(idx>0&&end===s.length-1){var parent=s.slice(0,idx).trim(),children=split(s.slice(idx+1,end));list.append(row(parent));if(children.length){var nested=make('div','ol-ing-nested');children.forEach(function(child){nested.append(row(child,'Listed within '+parent))});list.append(nested)}else list.append(row(s))}else list.append(row(s))});var max=7;if(chunks.length>max){Array.prototype.slice.call(list.children,max).forEach(function(n){n.hidden=true});var toggle=make('button','ol-ing-more','Show all ingredients');toggle.type='button';toggle.onclick=function(){var expand=toggle.textContent==='Show all ingredients';Array.prototype.slice.call(list.children,max).forEach(function(n){n.hidden=!expand});toggle.textContent=expand?'Show fewer ingredients':'Show all ingredients'};root.append(list,toggle)}else root.append(list);var raw=make('details','ol-ing-raw'),summary=make('summary','','View label text');raw.append(summary,make('p','',text));root.append(raw);return root}
window.OLIngredients={render:render,close:close};document.addEventListener('keydown',function(e){if(e.key==='Escape'&&sheet){e.stopPropagation();close()}} ,true);})();
