var R=require('../evidence-register.js');var n=0,f=0;
function t(name,ok){n++;if(!ok){f++;console.log('FAIL',name)}}
function clone(o){return JSON.parse(JSON.stringify(o))}
var base=clone(R.get('seed-oils-heart-outcomes'));
var infl=clone(R.get('seed-oils-inflammation'));
var NOW=new Date('2026-10-03');
t('seed oils heart record valid',R.validate(base).length===0);
t('heart outcomes yellow when watched',R.resolve(base,{topics:['seedoils'],now:NOW}).color==='yellow');
t('heart outcomes grey when not watched',R.resolve(base,{topics:[],now:NOW}).color==='grey');
t('unwatched chip says Listed',R.resolve(base,{topics:[],now:NOW}).chip==='Listed');
t('no ctx is grey',R.resolve(base,{now:NOW}).color==='grey');
t('overdue goes grey',R.resolve(base,{topics:['seedoils'],now:new Date('2027-04-02')}).note==='overdue');
var r;
t('inflammation record valid',R.validate(infl).length===0);
t('inflammation unsupported and grey when watched',R.resolve(infl,{topics:['seedoils'],now:NOW}).color==='grey'&&infl.status==='unsupported');
t('inflammation chip says not shown in trials',/Not shown in trials/.test(R.resolve(infl,{topics:['seedoils'],now:NOW}).chip));
t('inflammation chip is Listed when not watched',R.resolve(infl,{topics:[],now:NOW}).chip==='Listed');
r=clone(infl);r.color='yellow';t('unsupported with a color invalid',R.validate(r).some(function(x){return /unsupported has no color/.test(x)}));
r=clone(infl);r.sources=[r.sources[0]];t('unsupported with one source invalid',R.validate(r).some(function(x){return /unsupported needs/.test(x)}));
r=clone(base);r.sources=[r.sources[0]];t('yellow with one source invalid',R.validate(r).length>0);
r=clone(base);r.status='converging';t('yellow with converging invalid',R.validate(r).some(function(x){return /yellow requires/.test(x)}));
r=clone(base);r.color='orange';t('orange with contested invalid',R.validate(r).some(function(x){return /orange requires status/.test(x)}));
r=clone(base);r.color='orange';r.status='converging';t('orange with no amount invalid',R.validate(r).some(function(x){return /amount or context/.test(x)}));
r=clone(base);r.color='orange';r.status='converging';r.amount='Above 400 mg per day for adults, per label amount';t('orange fully specified valid',R.validate(r).length===0);
r=clone(base);r.color='green';r.status='converging';t('green with incomplete check invalid',R.validate(r).some(function(x){return /complete source check/.test(x)}));
r=clone(base);r.color='green';t('green without scope invalid',R.validate(r).some(function(x){return /green_scope/.test(x)}));
r=clone(base);r.color='red';t('red from general research invalid',R.validate(r).length>0);
r=clone(base);r.color='red';r.scope_type='product-specific';r.red_basis='official-source';t('red official product-specific valid',R.validate(r).length===0);
r=clone(base);delete r.reviewed_by;t('missing reviewer invalid',R.validate(r).length>0);
r=clone(base);r.shows=[];t('empty shows invalid',R.validate(r).length>0);
r=clone(base);r.does_not_show=[];t('empty does_not_show invalid',R.validate(r).length>0);
r=clone(base);r.next_review='soon';t('bad date invalid',R.validate(r).length>0);
r=clone(base);r.color='purple';t('unknown color invalid',R.validate(r).length>0);
r=clone(base);r.source_check.state='ok';t('unknown check state invalid',R.validate(r).length>0);
r=clone(base);r.sources=[];var o=R.resolve(r,{topics:['seedoils'],now:NOW});t('invalid record resolves grey with message',o.color==='grey'&&o.note==='invalid');
t('not found is not a pass for green',(function(){var g=clone(base);g.color='green';g.status='converging';g.green_scope='x';g.owner_signoff='2026-10-03';g.source_check.state='not found';return R.validate(g).some(function(x){return /complete source check/.test(x)})})());

/* new records and detectors */
['cured-meats-colorectal','synthetic-dyes-child-behavior'].forEach(function(id){t(id+' valid',R.validate(R.get(id)).length===0)});
var cm=R.get('cured-meats-colorectal'),dy=R.get('synthetic-dyes-child-behavior');
t('cured orange when watched',R.resolve(cm,{topics:['curedmeats'],now:NOW}).color==='orange');
t('cured grey when unwatched',R.resolve(cm,{topics:['dyes'],now:NOW}).color==='grey');
t('cured grey when not applicable',R.resolve(cm,{topics:['curedmeats'],now:NOW,applies:false}).note==='inapplicable');
t('dyes yellow when watched',R.resolve(dy,{topics:['dyes'],now:NOW}).color==='yellow');
t('dyes grey when unwatched',R.resolve(dy,{topics:[],now:NOW}).color==='grey');
r=clone(dy);delete r.sides;t('contested without sides invalid',R.validate(r).length>0);
r=clone(dy);r.sides.against=[];t('contested with one side empty invalid',R.validate(r).length>0);
t('detect nitrite in meat',R.detect('curedmeats','Pork, water, salt, sodium nitrite').found.indexOf('sodium nitrite')>=0);
t('detect celery with meat',R.detect('curedmeats','Beef, celery powder').found.indexOf('celery powder')>=0);
t('no celery-only without meat',R.detect('curedmeats','Vegetable broth, celery powder, salt').found.length===0);
t('celeryOnly flag',R.detect('curedmeats','Uncured bacon, celery powder').celeryOnly===true);
t('uncured word alone not a hit',R.detect('curedmeats','Uncured bacon, water, salt').found.length===0);
t('no meat flag',R.detect('curedmeats','Cheese, sodium nitrate').meat===false);
t('detect red 40',R.detect('dyes','Sugar, FD&C Red No. 40').found.length===1);
t('detect yellow 5 lake',R.detect('dyes','Yellow 5 Lake').found.length===1);
t('detect e129',R.detect('dyes','E129').found.length===1);
t('orange blossom not a dye',R.detect('dyes','Orange blossom water').found.length===0);
t('annatto and carmine not matched',R.detect('dyes','annatto, carmine, beet juice, turmeric').found.length===0);
t('red 30 not matched',R.detect('dyes','Red 30').found.length===0);
t('red 3 note',R.notesFor(dy,['red no. 3']).some(function(x){return /revoked/.test(x)}));
t('red 40 gets trial note not red 3 note',(function(){var n=R.notesFor(dy,['red 40']);return n.length===1&&/2007/.test(n[0])})());

/* sweeteners and added sugar records */
var NOW2=new Date('2026-10-03');
['aspartame-cancer','sweeteners-weight-disease','added-sugar-dental-caries','sugary-drinks-weight-diabetes'].forEach(function(id){
 var rr=R.get(id);t(id+' valid',!!rr&&R.validate(rr).length===0);
 t(id+' signed off by owner',rr.review_state==='reviewed'&&/Jesse Pringle/.test(rr.owner_signoff));
 var topic=rr.topic;
 t(id+' grey when not watched',R.resolve(rr,{topics:[],now:NOW2}).color==='grey');
 t(id+' shows color when watched',R.resolve(rr,{topics:[topic],now:NOW2}).color===rr.color);
 t(id+' grey and Listed-may-not-apply when it does not apply',R.resolve(rr,{topics:[topic],now:NOW2,applies:false}).chip==='Listed \u00b7 may not apply');
 t(id+' overdue goes grey',R.resolve(rr,{topics:[topic],now:new Date('2028-01-01')}).note==='overdue');
});
t('aspartame yellow unresolved',R.get('aspartame-cancer').color==='yellow'&&R.get('aspartame-cancer').status==='unresolved');
t('sweeteners yellow contested',R.get('sweeteners-weight-disease').color==='yellow'&&R.get('sweeteners-weight-disease').status==='contested');
t('sugar records orange converging with amount',['added-sugar-dental-caries','sugary-drinks-weight-diabetes'].every(function(i){var x=R.get(i);return x.color==='orange'&&x.status==='converging'&&x.amount.length>20}));
var d1=R.detect('sweeteners','water, aspartame, acesulfame potassium, erythritol, stevia leaf extract');
t('detect sweeteners splits sweeteners and polyols',d1.nss.length===3&&d1.polyols[0]==='erythritol'&&d1.aspartame.length===1);
t('polyol only list has no non-sugar sweetener',R.detect('sweeteners','maltitol, sorbitol').nss.length===0);
t('detect added sugar finds sugar words',R.detect('addedsugar','wheat flour, cane sugar, salt','Crackers').found.length===1);
t('detect added sugar marks a cola as a drink',R.detect('addedsugar','Carbonated water, high fructose corn syrup','Cola').drink===true);
t('cracker is not a drink',R.detect('addedsugar','wheat flour, sugar','Crackers').drink===false);
t('Pop-Tarts is not a drink',R.detect('addedsugar','flour, sugar','Pop-Tarts').drink===false);
t('no sugar words means nothing found',R.detect('addedsugar','water, salt','Broth').found.length===0);
t('drink detected from category',R.detect('addedsugar','water, sugar','Mountain Dew Sodas').drink===true);
t('snack category is not a drink',R.detect('addedsugar','flour, sugar','Pop-Tarts Snacks').drink===false);
['emulsifiers-gut-disease','carrageenan-gut-disease','ultra-processed-health'].forEach(function(id){var x=clone(R.get(id));
t(id+' valid',R.validate(x).length===0);
t(id+' signed off by owner',x.review_state==='reviewed'&&x.owner_signoff==='2026-10-03 Jesse Pringle');
t(id+' yellow, not orange',x.color==='yellow');
t(id+' grey when not watched',R.resolve(x,{topics:[],now:NOW}).color==='grey');
t(id+' yellow when watched',R.resolve(x,{topics:[x.topic],now:NOW}).color==='yellow');
t(id+' not-apply chip',R.resolve(x,{topics:[x.topic],now:NOW,applies:false}).chip==='Listed \u00b7 may not apply');
t(id+' overdue grey',R.resolve(x,{topics:[x.topic],now:new Date('2027-04-05')}).note==='overdue');
t(id+' has sources on both sides',x.sides['for'].length>=2&&x.sides.against.length>=2&&x.sources.length>=5)});
['natural-flavors-health','additives-label-review'].forEach(function(id){var x=clone(R.get(id));
t(id+' valid',R.validate(x).length===0);
t(id+' owner signed off 2026-10-03',x.review_state==='reviewed'&&x.owner_signoff==='2026-10-03 Jesse Pringle');
t(id+' grey never green or orange',x.color==='grey');
t(id+' chip says no evidence finding',R.resolve(x,{topics:[x.topic],now:NOW}).chip==='No evidence finding');
t(id+' reason says not a finding of safety or harm',/not (a finding|yet reviewed)|does not mean harmful/i.test(x.color_reason));
t(id+' overdue goes grey',R.resolve(x,{topics:[x.topic],now:new Date('2027-04-05')}).note==='overdue');
t(id+' has 5+ sources',x.sources.length>=5)});
['bha-cancer','bht-intake','sulfites-sensitivity','propylparaben-endocrine','caramel-color-4mei','msg-glutamate','phosphate-additives'].forEach(function(id){var x=clone(R.get(id));
t(id+' valid',R.validate(x).length===0);
t(id+' provisional, no signoff',x.review_state==='provisional'&&x.owner_signoff===null);
t(id+' additives topic, 2+ sources',x.topic==='additives'&&x.sources.length>=2);
t(id+' grey when additives not watched',R.resolve(x,{topics:[],now:NOW}).color==='grey');
t(id+' own color when watched',R.resolve(x,{topics:['additives'],now:NOW}).color===x.color);
t(id+' overdue grey',R.resolve(x,{topics:['additives'],now:new Date('2027-04-05')}).note==='overdue')});
t('sulfites orange converging',R.get('sulfites-sensitivity').color==='orange'&&R.get('sulfites-sensitivity').status==='converging');
t('caramel and msg contested with both sides',['caramel-color-4mei','msg-glutamate'].every(function(i){var x=R.get(i);return x.status==='contested'&&x.sides['for'].length>=2&&x.sides.against.length>=2}));
var D=R.detect('additives','sodium bisulfite, caramel color, phosphoric acid, MSG, BHT, BHA, propylparaben','');
t('detect new additives',D.sulfite.length&&D.caramel.length&&D.phosphate.length&&D.msg.length&&D.bht.length&&D.bha.length&&D.propylparaben.length);
t('detect no false hit on plain text',R.detect('additives','water, sugar, salt','').found.length===0);
['titanium-dioxide-genotoxicity','potassium-bromate-cancer','benzoate-preservatives-intake'].forEach(function(id){var x=clone(R.get(id));
t(id+' valid',R.validate(x).length===0);
t(id+' owner signed off 2026-10-03',x.review_state==='reviewed'&&x.owner_signoff==='2026-10-03 Jesse Pringle');
t(id+' yellow',x.color==='yellow'&&x.topic==='additives');
t(id+' grey when additives not watched',R.resolve(x,{topics:[],now:NOW}).color==='grey');
t(id+' yellow when watched',R.resolve(x,{topics:['additives'],now:NOW}).color==='yellow');
t(id+' overdue grey',R.resolve(x,{topics:['additives'],now:new Date('2027-04-05')}).note==='overdue')});
var ad1=R.detect('additives','Carbonated water, sodium benzoate, erythorbic acid, titanium dioxide, E924');
t('detect additives finds titanium dioxide',ad1.tio2.length===1);
t('detect additives finds bromate code',ad1.bromate.length===1);
t('detect benzene flag needs benzoate and ascorbate',ad1.benzene===true&&R.detect('additives','sodium benzoate, water').benzene===false);
t('detect additives ignores plain list',R.detect('additives','water, salt, flour').found.length===0);
t('toxicity record about titanium oxide not matching zinc oxide',R.detect('additives','zinc oxide').tio2.length===0);

console.log(n+' cases, '+f+' failed');process.exit(f?1:0);
